<<<<<<< HEAD
# HW5 SETUP
apriltags:  
  - id: 0
    # Position in map frame (meters)
    x: 2.5
    y: 0.2
=======
apriltags:  
  - id: 5
    # Position in map frame (meters)
    x: 2.5
    y: 0.0
>>>>>>> 07b5e62bd667773a3fcd521c8267e3f2a3114870
    z: 0.1
    # Orientation in map frame (quaternion)
    qx: 0.5
    qy: -0.5
    qz: -0.5
    qw: 0.5
<<<<<<< HEAD
  - id: 8
    # Position in map frame (meters)
    x: 2.5
    y: 1.3
=======
  - id: 1
    # Position in map frame (meters)
    x: 2.5
    y: 1.5
>>>>>>> 07b5e62bd667773a3fcd521c8267e3f2a3114870
    z: 0.1
    # Orientation in map frame (quaternion)
    qx: 0.5
    qy: -0.5
    qz: -0.5
    qw: 0.5
<<<<<<< HEAD
  - id: 2
    # Position in map frame (meters)
    x: 2.5
    y: 2.3
    z: 0.2
=======
  - id: 11
    # Position in map frame (meters)
    x: 1.10
    y: 1.25
    z: 0
>>>>>>> 07b5e62bd667773a3fcd521c8267e3f2a3114870
    # Orientation in map frame (quaternion)
    qx: 0.5
    qy: -0.5
    qz: -0.5
    qw: 0.5


  - id: 3
    # Position in map frame (meters)
<<<<<<< HEAD
    x: 2.3
=======
    x: 2.0
>>>>>>> 07b5e62bd667773a3fcd521c8267e3f2a3114870
    y: 2.5
    z: 0.1
    # Orientation in map frame (quaternion)
    qx: 0.707
    qy: 0.0
    qz: 0.0
    qw: 0.707
<<<<<<< HEAD
  - id: 4
    # Position in map frame (meters)
    x: 1.2
    y: 2.5
    z: 0.1
    # Orientation in map frame (quaternion)
    qx: 0.707
    qy: 0.0
    qz: 0.0
    qw: 0.707
  - id: 5
    # Position in map frame (meters)
    x: 0.2
    y: 2.5
    z: 0.1
    # Orientation in map frame (quaternion)
    qx: 0.707
    qy: 0.0
    qz: 0.0
    qw: 0.707




  - id: 1
    # Position in map frame (meters)
    x: 0
    y: 2.3
    z: 0.1
    # Orientation in map frame (quaternion)
    qx: 0.5
    qy: 0.5
    qz: 0.5
    qw: 0.5
  - id: 6
    # Position in map frame (meters)
    x: 0
    y: 1.3
    z: 0.1
    # Orientation in map frame (quaternion)
    qx: 0.5
    qy: 0.5
    qz: 0.5
    qw: 0.5
  - id: 7
    # Position in map frame (meters)
    x: 0
    y: 0.2
    z: 0.1
    # Orientation in map frame (quaternion)
    qx: 0.5
    qy: 0.5
    qz: 0.5
    qw: 0.5



  - id: 9
    # Position in map frame (meters)
    x: 2.3
    y: 0
    z: 0.1
    # Orientation in map frame (quaternion)
    qx: 0
    qy: 0.707
    qz: 0.707
    qw: 0
  - id: 10
    # Position in map frame (meters)
    x: 1.3
    y: 0
    z: 0.1
    # Orientation in map frame (quaternion)
    qx: 0
    qy: 0.707
    qz: 0.707
    qw: 0
  - id: 11
    # Position in map frame (meters)
    x: 0.2
    y: 0
    z: 0.1
=======
  - id: 10
    # Position in map frame (meters)
    x: 1.25
    y: 1.10
    z: 0.0
    # Orientation in map frame (quaternion)
    qx: 0.707
    qy: 0.0
    qz: 0.0
    qw: 0.707
  - id: 7
    # Position in map frame (meters)
    x: 0.5
    y: 2.5
    z: 0.0
    # Orientation in map frame (quaternion)
    qx: 0.707
    qy: 0.0
    qz: 0.0
    qw: 0.707

  - id: 4
    # Position in map frame (meters)
    x: 2.0
    y: -0.5
    z: 0.0
    # Orientation in map frame (quaternion)
    qx: 0.0
    qy: 0.707
    qz: 0.707
    qw: 0.0




  - id: 13
    # Position in map frame (meters)
    x: 1.50
    y: 1.25
    z: 0
    # Orientation in map frame (quaternion)
    qx: 0.5
    qy: 0.5
    qz: 0.5
    qw: 0.5

  - id: 8
    # Position in map frame (meters)
    x: -0.5
    y: 1.25
    z: 0
    # Orientation in map frame (quaternion)
    qx: 0.5
    qy: 0.5
    qz: 0.5
    qw: 0.5
  # - id: 14
  #   # Position in map frame (meters)
  #   x: 0
  #   y: 0
  #   z: 0
  #   # Orientation in map frame (quaternion)
  #   qx: 0.5
  #   qy: 0.5
  #   qz: 0.5
  #   qw: 0.5



  - id: 12
    # Position in map frame (meters)
    x: 1.25
    y: 1.50
    z: 0
>>>>>>> 07b5e62bd667773a3fcd521c8267e3f2a3114870
    # Orientation in map frame (quaternion)
    qx: 0
    qy: 0.707
    qz: 0.707
    qw: 0
<<<<<<< HEAD
#---------------------------------------------------------HW 4 setup1
# apriltags:  
#   - id: 3
#     x: 2.43
#     y: 0.5
#     z: 0.0
#     qx: 0.5
#     qy: -0.5
#     qz: -0.5
#     qw: 0.5
#   - id: 4
#     x: 2.43
#     y: 1.93
#     z: 0.0
#     qx: 0.5
#     qy: -0.5
#     qz: -0.5
#     qw: 0.5
#   - id: 5
#     x: 1.93
#     y: 2.43
#     z: 0.0
#     qx: 0.707
#     qy: 0.0
#     qz: 0.0
#     qw: 0.707
#   - id: 7
#     x: 0.5
#     y: 2.43
#     z: 0.0
#     qx: 0.707 
#     qy: 0.0
#     qz: 0.0
#     qw: 0.707
#   - id: 8
#     x: 0.0
#     y: 1.93
#     z: 0.0
#     qx: 0.5
#     qy: 0.5
#     qz: 0.5
#     qw: 0.5
#   - id: 1
#     x: 0.5
#     y: 0.0
#     z: 0.0
#     qx: 0.0
#     qy: 0.707
#     qz: 0.707
#     qw: 0.0
#   - id: 2
#     x: 1.93
#     y: 0.0
#     z: 0.0
#     qx: 0.0
#     qy: 0.707
#     qz: 0.707
#     qw: 0.0
    
# # obstacles
#   - id: 0
#     x: 1.21
#     y: 1.06
#     z: 0.0
#     qx: 0.707 
#     qy: 0.0
#     qz: 0.0
#     qw: 0.707

#   - id: 10
#     x: 1.36
#     y: 1.21
#     z: 0.0
#     qx: 0.5
#     qy: 0.5
#     qz: 0.5
#     qw: 0.5

#   - id: 11
#     x: 1.21
#     y: 1.36
#     z: 0.0
#     qx: 0.0
#     qy: 0.707
#     qz: 0.707
#     qw: 0.0

#   - id: 12
#     x: 1.06
#     y: 1.21
#     z: 0.0
#     qx: 0.5
#     qy: -0.5
#     qz: -0.5
#     qw: 0.5









# #---------------------------------------------------------HW 4 setup2



#     apriltags:  
#     - id: 3
#       x: 2.43
#       y: 0.5
#       z: 0.0
#       qx: 0.5
#       qy: -0.5
#       qz: -0.5
#       qw: 0.5
#     - id: 4
#       x: 2.43
#       y: 1.93
#       z: 0.0
#       qx: 0.5
#       qy: -0.5
#       qz: -0.5
#       qw: 0.5
#     - id: 5
#       x: 1.93
#       y: 2.43
#       z: 0.0
#       qx: 0.707
#       qy: 0.0
#       qz: 0.0
#       qw: 0.707
#     - id: 7
#       x: 0.5
#       y: 2.43
#       z: 0.0
#       qx: 0.707 
#       qy: 0.0
#       qz: 0.0
#       qw: 0.707
#     - id: 8
#       x: 0.0
#       y: 1.93
#       z: 0.0
#       qx: 0.5
#       qy: 0.5
#       qz: 0.5
#       qw: 0.5
#     - id: 1
#       x: 0.5
#       y: 0.0
#       z: 0.0
#       qx: 0.0
#       qy: 0.707
#       qz: 0.707
#       qw: 0.0
#     - id: 2
#       x: 1.93
#       y: 0.0
#       z: 0.0
#       qx: 0.0
#       qy: 0.707
#       qz: 0.707
#       qw: 0.0
      
#   # obstacles
#     - id: 0
#       x: 1.21
#       y: 1.06
#       z: 0.0
#       qx: 0.707 
#       qy: 0.0
#       qz: 0.0
#       qw: 0.707
  
#     - id: 10
#       x: 1.36
#       y: 1.21
#       z: 0.0
#       qx: 0.5
#       qy: 0.5
#       qz: 0.5
#       qw: 0.5
  
#     - id: 11
#       x: 1.21
#       y: 1.36
#       z: 0.0
#       qx: 0.0
#       qy: 0.707
#       qz: 0.707
#       qw: 0.0
  
#     - id: 12
#       x: 1.06
#       y: 1.21
#       z: 0.0
#       qx: 0.5
#       qy: -0.5
#       qz: -0.5
#       qw: 0.5
  
  
=======
  
>>>>>>> 07b5e62bd667773a3fcd521c8267e3f2a3114870
