apriltags:  
  - id: 5
    # Position in map frame (meters)
    x: 2.5
    y: 0.0
    z: 0.1
    # Orientation in map frame (quaternion)
    qx: 0.5
    qy: -0.5
    qz: -0.5
    qw: 0.5
  - id: 1
    # Position in map frame (meters)
    x: 2.5
    y: 1.5
    z: 0.1
    # Orientation in map frame (quaternion)
    qx: 0.5
    qy: -0.5
    qz: -0.5
    qw: 0.5
  - id: 11
    # Position in map frame (meters)
    x: 1.10
    y: 1.25
    z: 0
    # Orientation in map frame (quaternion)
    qx: 0.5
    qy: -0.5
    qz: -0.5
    qw: 0.5


  - id: 3
    # Position in map frame (meters)
    x: 2.0
    y: 2.5
    z: 0.1
    # Orientation in map frame (quaternion)
    qx: 0.707
    qy: 0.0
    qz: 0.0
    qw: 0.707
  - id: 10
    # Position in map frame (meters)
    x: 1.25
    y: 1.10
    z: 0.0
    # Orientation in map frame (quaternion)
    qx: 0.707
    qy: 0.0
    qz: 0.0
    qw: 0.707
  - id: 7
    # Position in map frame (meters)
    x: 0.5
    y: 2.5
    z: 0.0
    # Orientation in map frame (quaternion)
    qx: 0.707
    qy: 0.0
    qz: 0.0
    qw: 0.707

  - id: 4
    # Position in map frame (meters)
    x: 2.0
    y: -0.5
    z: 0.0
    # Orientation in map frame (quaternion)
    qx: 0.0
    qy: 0.707
    qz: 0.707
    qw: 0.0




  - id: 13
    # Position in map frame (meters)
    x: 1.50
    y: 1.25
    z: 0
    # Orientation in map frame (quaternion)
    qx: 0.5
    qy: 0.5
    qz: 0.5
    qw: 0.5

  - id: 8
    # Position in map frame (meters)
    x: -0.5
    y: 1.25
    z: 0
    # Orientation in map frame (quaternion)
    qx: 0.5
    qy: 0.5
    qz: 0.5
    qw: 0.5
  # - id: 14
  #   # Position in map frame (meters)
  #   x: 0
  #   y: 0
  #   z: 0
  #   # Orientation in map frame (quaternion)
  #   qx: 0.5
  #   qy: 0.5
  #   qz: 0.5
  #   qw: 0.5



  - id: 12
    # Position in map frame (meters)
    x: 1.25
    y: 1.50
    z: 0
    # Orientation in map frame (quaternion)
    qx: 0
    qy: 0.707
    qz: 0.707
    qw: 0
  
